spring:
  profiles:
    activate:
      on-profile: local
  jpa:
    database: mysql
    hibernate.ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql : true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: ss49594959
    hikari:
      maximum-pool-size: 50 #최대 pool 크기
      minimum-idle: 50 #최소 pool 크기
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#      springframework:
#        orm:
#          jpa: DEBUG
